package oracle.sql;

public class ZONEIDMAP
{
  private static TableClass zoneid = new TableClass(544, 0.99F);
  protected static final int INV_ZONEID = -1;

  public static int getID(String paramString)
  {
    int i = 0;
    Integer localInteger = zoneid.getID(paramString);

    if (localInteger == null)
      i = -1;
    else
      i = localInteger.intValue();
    return i;
  }

  public static String getRegion(int paramInt)
  {
    String str = zoneid.getZone(Integer.valueOf(paramInt));

    if (str == null)
    {
      str = zoneid.getOldZone(Integer.valueOf(paramInt));
    }

    return str;
  }

  public static boolean isValidID(int paramInt)
  {
    if (getRegion(paramInt) == null) {
      return false;
    }
    return true;
  }

  public static boolean isValidRegion(String paramString)
  {
    if (getID(paramString) == -1) {
      return false;
    }
    return true;
  }

  static
  {
    zoneid.put("Africa/Asmera", Integer.valueOf(46));
    zoneid.put("Africa/Bamako", Integer.valueOf(58));
    zoneid.put("Africa/Bangui", Integer.valueOf(37));
    zoneid.put("Africa/Banjul", Integer.valueOf(49));
    zoneid.put("Africa/Bissau", Integer.valueOf(52));
    zoneid.put("Africa/Blantyre", Integer.valueOf(57));
    zoneid.put("Africa/Bujumbura", Integer.valueOf(35));
    zoneid.put("Africa/Cairo", Integer.valueOf(44));
    zoneid.put("Africa/Casablanca", Integer.valueOf(61));
    zoneid.put("Africa/Conakry", Integer.valueOf(51));
    zoneid.put("Africa/Dakar", Integer.valueOf(69));
    zoneid.put("Africa/Dar_es_Salaam", Integer.valueOf(75));
    zoneid.put("Africa/Djibouti", Integer.valueOf(43));
    zoneid.put("Africa/Douala", Integer.valueOf(36));
    zoneid.put("Africa/Freetown", Integer.valueOf(70));
    zoneid.put("Africa/Gaborone", Integer.valueOf(33));
    zoneid.put("Africa/Harare", Integer.valueOf(80));
    zoneid.put("Africa/Johannesburg", Integer.valueOf(72));
    zoneid.put("Africa/Kampala", Integer.valueOf(78));
    zoneid.put("Africa/Khartoum", Integer.valueOf(73));
    zoneid.put("Africa/Kigali", Integer.valueOf(67));
    zoneid.put("Africa/Kinshasa", Integer.valueOf(39));
    zoneid.put("Africa/Lagos", Integer.valueOf(66));
    zoneid.put("Africa/Libreville", Integer.valueOf(48));
    zoneid.put("Africa/Lome", Integer.valueOf(76));
    zoneid.put("Africa/Luanda", Integer.valueOf(31));
    zoneid.put("Africa/Lubumbashi", Integer.valueOf(40));
    zoneid.put("Africa/Lusaka", Integer.valueOf(79));
    zoneid.put("Africa/Malabo", Integer.valueOf(45));
    zoneid.put("Africa/Maputo", Integer.valueOf(63));
    zoneid.put("Africa/Maseru", Integer.valueOf(54));
    zoneid.put("Africa/Mbabane", Integer.valueOf(74));
    zoneid.put("Africa/Mogadishu", Integer.valueOf(71));
    zoneid.put("Africa/Monrovia", Integer.valueOf(55));
    zoneid.put("Africa/Nairobi", Integer.valueOf(53));
    zoneid.put("Africa/Ndjamena", Integer.valueOf(38));
    zoneid.put("Africa/Niamey", Integer.valueOf(65));
    zoneid.put("Africa/Nouakchott", Integer.valueOf(60));
    zoneid.put("Africa/Ouagadougou", Integer.valueOf(34));
    zoneid.put("Africa/Porto-Novo", Integer.valueOf(32));
    zoneid.put("Africa/Sao_Tome", Integer.valueOf(68));
    zoneid.put("Africa/Timbuktu", Integer.valueOf(59));
    zoneid.put("Africa/Tripoli", Integer.valueOf(56));
    zoneid.put("Africa/Tunis", Integer.valueOf(77));
    zoneid.put("Africa/Windhoek", Integer.valueOf(64));

    zoneid.put("America/Adak", Integer.valueOf(108));
    zoneid.put("America/Anchorage", Integer.valueOf(106));
    zoneid.put("America/Anguilla", Integer.valueOf(146));
    zoneid.put("America/Antigua", Integer.valueOf(147));
    zoneid.put("America/Aruba", Integer.valueOf(181));
    zoneid.put("America/Asuncion", Integer.valueOf(200));
    zoneid.put("America/Barbados", Integer.valueOf(149));
    zoneid.put("America/Belize", Integer.valueOf(150));
    zoneid.put("America/Bogota", Integer.valueOf(195));
    zoneid.put("America/Buenos_Aires", Integer.valueOf(175));
    zoneid.put("America/Argentina/Buenos_Aires", Integer.valueOf(687));
    zoneid.put("America/Caracas", Integer.valueOf(205));
    zoneid.put("America/Cayenne", Integer.valueOf(198));
    zoneid.put("America/Cayman", Integer.valueOf(151));
    zoneid.put("America/Chicago", Integer.valueOf(101));
    zoneid.put("America/Costa_Rica", Integer.valueOf(152));
    zoneid.put("America/Cuiaba", Integer.valueOf(189));
    zoneid.put("America/Curacao", Integer.valueOf(196));
    zoneid.put("America/Dawson_Creek", Integer.valueOf(131));
    zoneid.put("America/Denver", Integer.valueOf(102));
    zoneid.put("America/Dominica", Integer.valueOf(154));
    zoneid.put("America/Edmonton", Integer.valueOf(129));
    zoneid.put("America/El_Salvador", Integer.valueOf(156));
    zoneid.put("America/Fortaleza", Integer.valueOf(185));
    zoneid.put("America/Godthab", Integer.valueOf(207));
    zoneid.put("America/Grand_Turk", Integer.valueOf(172));
    zoneid.put("America/Grenada", Integer.valueOf(157));
    zoneid.put("America/Guadeloupe", Integer.valueOf(158));
    zoneid.put("America/Guatemala", Integer.valueOf(159));
    zoneid.put("America/Guayaquil", Integer.valueOf(197));
    zoneid.put("America/Guyana", Integer.valueOf(199));
    zoneid.put("America/Halifax", Integer.valueOf(120));
    zoneid.put("America/Havana", Integer.valueOf(153));
    zoneid.put("America/Indianapolis", Integer.valueOf(111));
    zoneid.put("America/Jamaica", Integer.valueOf(162));
    zoneid.put("America/La_Paz", Integer.valueOf(182));
    zoneid.put("America/Lima", Integer.valueOf(201));
    zoneid.put("America/Los_Angeles", Integer.valueOf(103));
    zoneid.put("America/Managua", Integer.valueOf(165));
    zoneid.put("America/Manaus", Integer.valueOf(192));
    zoneid.put("America/Martinique", Integer.valueOf(163));
    zoneid.put("America/Mazatlan", Integer.valueOf(144));
    zoneid.put("America/Mexico_City", Integer.valueOf(141));
    zoneid.put("America/Miquelon", Integer.valueOf(170));
    zoneid.put("America/Montevideo", Integer.valueOf(204));
    zoneid.put("America/Montreal", Integer.valueOf(122));
    zoneid.put("America/Montserrat", Integer.valueOf(164));
    zoneid.put("America/Nassau", Integer.valueOf(148));
    zoneid.put("America/New_York", Integer.valueOf(100));
    zoneid.put("America/Noronha", Integer.valueOf(183));
    zoneid.put("America/Panama", Integer.valueOf(166));
    zoneid.put("America/Paramaribo", Integer.valueOf(202));
    zoneid.put("America/Phoenix", Integer.valueOf(109));
    zoneid.put("America/Port-au-Prince", Integer.valueOf(160));
    zoneid.put("America/Port_of_Spain", Integer.valueOf(203));
    zoneid.put("America/Porto_Acre", Integer.valueOf(193));
    zoneid.put("America/Puerto_Rico", Integer.valueOf(167));
    zoneid.put("America/Regina", Integer.valueOf(127));
    zoneid.put("America/Santiago", Integer.valueOf(194));
    zoneid.put("America/Santo_Domingo", Integer.valueOf(155));
    zoneid.put("America/Sao_Paulo", Integer.valueOf(188));
    zoneid.put("America/Scoresbysund", Integer.valueOf(206));
    zoneid.put("America/St_Johns", Integer.valueOf(118));
    zoneid.put("America/St_Kitts", Integer.valueOf(168));
    zoneid.put("America/St_Lucia", Integer.valueOf(169));
    zoneid.put("America/St_Thomas", Integer.valueOf(174));
    zoneid.put("America/St_Vincent", Integer.valueOf(171));
    zoneid.put("America/Tegucigalpa", Integer.valueOf(161));
    zoneid.put("America/Thule", Integer.valueOf(208));
    zoneid.put("America/Tijuana", Integer.valueOf(145));
    zoneid.put("America/Tortola", Integer.valueOf(173));
    zoneid.put("America/Vancouver", Integer.valueOf(130));
    zoneid.put("America/Winnipeg", Integer.valueOf(126));
    zoneid.put("PST", Integer.valueOf(2151));
    zoneid.put("EST", Integer.valueOf(211));
    zoneid.put("CST", Integer.valueOf(1637));

    zoneid.put("Antarctica/Casey", Integer.valueOf(230));
    zoneid.put("Antarctica/DumontDUrville", Integer.valueOf(233));
    zoneid.put("Antarctica/Mawson", Integer.valueOf(232));
    zoneid.put("Antarctica/McMurdo", Integer.valueOf(236));
    zoneid.put("Antarctica/Palmer", Integer.valueOf(235));

    zoneid.put("Asia/Aden", Integer.valueOf(302));
    zoneid.put("Asia/Amman", Integer.valueOf(268));
    zoneid.put("Asia/Anadyr", Integer.valueOf(312));
    zoneid.put("Asia/Aqtau", Integer.valueOf(271));
    zoneid.put("Asia/Aqtobe", Integer.valueOf(270));
    zoneid.put("Asia/Ashkhabad", Integer.valueOf(297));
    zoneid.put("Asia/Baghdad", Integer.valueOf(265));
    zoneid.put("Asia/Bahrain", Integer.valueOf(243));
    zoneid.put("Asia/Baku", Integer.valueOf(242));
    zoneid.put("Asia/Bangkok", Integer.valueOf(296));
    zoneid.put("Asia/Beirut", Integer.valueOf(277));
    zoneid.put("Asia/Bishkek", Integer.valueOf(272));
    zoneid.put("Asia/Brunei", Integer.valueOf(246));
    zoneid.put("Asia/Calcutta", Integer.valueOf(260));
    zoneid.put("Asia/Colombo", Integer.valueOf(293));
    zoneid.put("Asia/Dacca", Integer.valueOf(244));
    zoneid.put("Asia/Damascus", Integer.valueOf(294));
    zoneid.put("Asia/Dubai", Integer.valueOf(298));
    zoneid.put("Asia/Dushanbe", Integer.valueOf(295));
    zoneid.put("Asia/Hong_Kong", Integer.valueOf(254));
    zoneid.put("Asia/Irkutsk", Integer.valueOf(307));
    zoneid.put("Asia/Jakarta", Integer.valueOf(261));
    zoneid.put("Asia/Jayapura", Integer.valueOf(263));
    zoneid.put("Asia/Jerusalem", Integer.valueOf(266));
    zoneid.put("Asia/Kabul", Integer.valueOf(240));
    zoneid.put("Asia/Kamchatka", Integer.valueOf(311));
    zoneid.put("Asia/Karachi", Integer.valueOf(284));
    zoneid.put("Asia/Katmandu", Integer.valueOf(282));
    zoneid.put("Asia/Krasnoyarsk", Integer.valueOf(306));
    zoneid.put("Asia/Kuala_Lumpur", Integer.valueOf(278));
    zoneid.put("Asia/Kuwait", Integer.valueOf(275));
    zoneid.put("Asia/Macao", Integer.valueOf(256));
    zoneid.put("Asia/Magadan", Integer.valueOf(310));
    zoneid.put("Asia/Manila", Integer.valueOf(286));
    zoneid.put("Asia/Muscat", Integer.valueOf(283));
    zoneid.put("Asia/Nicosia", Integer.valueOf(257));
    zoneid.put("Asia/Novosibirsk", Integer.valueOf(305));
    zoneid.put("Asia/Phnom_Penh", Integer.valueOf(248));
    zoneid.put("Asia/Pyongyang", Integer.valueOf(274));
    zoneid.put("Asia/Qatar", Integer.valueOf(287));
    zoneid.put("Asia/Rangoon", Integer.valueOf(247));
    zoneid.put("Asia/Riyadh", Integer.valueOf(288));
    zoneid.put("Asia/Saigon", Integer.valueOf(301));
    zoneid.put("Asia/Seoul", Integer.valueOf(273));
    zoneid.put("Asia/Shanghai", Integer.valueOf(250));
    zoneid.put("Asia/Singapore", Integer.valueOf(292));
    zoneid.put("Asia/Taipei", Integer.valueOf(255));
    zoneid.put("Asia/Tashkent", Integer.valueOf(300));
    zoneid.put("Asia/Tbilisi", Integer.valueOf(258));
    zoneid.put("Asia/Tehran", Integer.valueOf(264));
    zoneid.put("Asia/Thimbu", Integer.valueOf(245));
    zoneid.put("Asia/Tokyo", Integer.valueOf(267));
    zoneid.put("Asia/Ujung_Pandang", Integer.valueOf(262));
    zoneid.put("Asia/Ulan_Bator", Integer.valueOf(793));
    zoneid.put("Asia/Vientiane", Integer.valueOf(276));
    zoneid.put("Asia/Vladivostok", Integer.valueOf(309));
    zoneid.put("Asia/Yakutsk", Integer.valueOf(308));
    zoneid.put("Asia/Yekaterinburg", Integer.valueOf(303));
    zoneid.put("Asia/Yerevan", Integer.valueOf(241));

    zoneid.put("Atlantic/Azores", Integer.valueOf(336));
    zoneid.put("Atlantic/Bermuda", Integer.valueOf(330));
    zoneid.put("Atlantic/Canary", Integer.valueOf(338));
    zoneid.put("Atlantic/Cape_Verde", Integer.valueOf(339));
    zoneid.put("Atlantic/Faeroe", Integer.valueOf(333));
    zoneid.put("Atlantic/Jan_Mayen", Integer.valueOf(335));
    zoneid.put("Atlantic/Reykjavik", Integer.valueOf(334));
    zoneid.put("Atlantic/South_Georgia", Integer.valueOf(332));
    zoneid.put("Atlantic/St_Helena", Integer.valueOf(340));
    zoneid.put("Atlantic/Stanley", Integer.valueOf(331));

    zoneid.put("Australia/Adelaide", Integer.valueOf(349));
    zoneid.put("Australia/Brisbane", Integer.valueOf(347));
    zoneid.put("Australia/Darwin", Integer.valueOf(345));
    zoneid.put("Australia/Perth", Integer.valueOf(346));
    zoneid.put("Australia/Sydney", Integer.valueOf(352));
    zoneid.put("Australia/ACT", Integer.valueOf(864));

    zoneid.put("EET", Integer.valueOf(368));
    zoneid.put("GMT", Integer.valueOf(513));
    zoneid.put("UTC", Integer.valueOf(5121));
    zoneid.put("MET", Integer.valueOf(367));
    zoneid.put("MST", Integer.valueOf(212));
    zoneid.put("HST", Integer.valueOf(213));

    zoneid.put("Europe/Amsterdam", Integer.valueOf(396));
    zoneid.put("Europe/Andorra", Integer.valueOf(373));
    zoneid.put("Europe/Athens", Integer.valueOf(385));
    zoneid.put("Europe/Belgrade", Integer.valueOf(412));
    zoneid.put("Europe/Berlin", Integer.valueOf(383));
    zoneid.put("Europe/Brussels", Integer.valueOf(376));
    zoneid.put("Europe/Bucharest", Integer.valueOf(400));
    zoneid.put("Europe/Budapest", Integer.valueOf(386));
    zoneid.put("Europe/Chisinau", Integer.valueOf(393));
    zoneid.put("Europe/Copenhagen", Integer.valueOf(379));
    zoneid.put("Europe/Dublin", Integer.valueOf(371));
    zoneid.put("Europe/Gibraltar", Integer.valueOf(384));
    zoneid.put("Europe/Guernsey", Integer.valueOf(2417));
    zoneid.put("Europe/Helsinki", Integer.valueOf(381));
    zoneid.put("Isle_of_Man", Integer.valueOf(2929));
    zoneid.put("Europe/Istanbul", Integer.valueOf(407));
    zoneid.put("Europe/Jersey", Integer.valueOf(1905));
    zoneid.put("Europe/Kaliningrad", Integer.valueOf(401));
    zoneid.put("Europe/Kiev", Integer.valueOf(408));
    zoneid.put("Europe/Lisbon", Integer.valueOf(399));
    zoneid.put("Europe/London", Integer.valueOf(369));
    zoneid.put("Europe/Luxembourg", Integer.valueOf(391));
    zoneid.put("Europe/Madrid", Integer.valueOf(404));
    zoneid.put("Europe/Malta", Integer.valueOf(392));
    zoneid.put("Europe/Mariehamn", Integer.valueOf(893));
    zoneid.put("Europe/Minsk", Integer.valueOf(375));
    zoneid.put("Europe/Monaco", Integer.valueOf(395));
    zoneid.put("Europe/Moscow", Integer.valueOf(402));
    zoneid.put("Europe/Oslo", Integer.valueOf(397));
    zoneid.put("Europe/Paris", Integer.valueOf(382));
    zoneid.put("Europe/Podgorica", Integer.valueOf(2972));
    zoneid.put("Europe/Prague", Integer.valueOf(378));
    zoneid.put("Europe/Riga", Integer.valueOf(388));
    zoneid.put("Europe/Rome", Integer.valueOf(387));
    zoneid.put("Europe/Samara", Integer.valueOf(403));
    zoneid.put("Europe/Simferopol", Integer.valueOf(411));
    zoneid.put("Europe/Sofia", Integer.valueOf(377));
    zoneid.put("Europe/Stockholm", Integer.valueOf(405));
    zoneid.put("Europe/Tallinn", Integer.valueOf(380));
    zoneid.put("Europe/Tirane", Integer.valueOf(372));
    zoneid.put("Europe/Vaduz", Integer.valueOf(389));
    zoneid.put("Europe/Vienna", Integer.valueOf(374));
    zoneid.put("Europe/Vilnius", Integer.valueOf(390));
    zoneid.put("Europe/Volgograd", Integer.valueOf(413));
    zoneid.put("Europe/Warsaw", Integer.valueOf(398));
    zoneid.put("Europe/Zurich", Integer.valueOf(406));

    zoneid.put("Indian/Antananarivo", Integer.valueOf(438));
    zoneid.put("Indian/Chagos", Integer.valueOf(436));
    zoneid.put("Indian/Christmas", Integer.valueOf(439));
    zoneid.put("Indian/Cocos", Integer.valueOf(440));
    zoneid.put("Indian/Comoro", Integer.valueOf(441));
    zoneid.put("Indian/Kerguelen", Integer.valueOf(435));
    zoneid.put("Indian/Mahe", Integer.valueOf(442));
    zoneid.put("Indian/Maldives", Integer.valueOf(437));
    zoneid.put("Indian/Mauritius", Integer.valueOf(443));
    zoneid.put("Indian/Mayotte", Integer.valueOf(444));
    zoneid.put("Indian/Reunion", Integer.valueOf(445));

    zoneid.put("Pacific/Apia", Integer.valueOf(479));
    zoneid.put("Pacific/Auckland", Integer.valueOf(471));
    zoneid.put("Pacific/Chatham", Integer.valueOf(472));
    zoneid.put("Pacific/Easter", Integer.valueOf(451));
    zoneid.put("Pacific/Efate", Integer.valueOf(488));
    zoneid.put("Pacific/Enderbury", Integer.valueOf(460));
    zoneid.put("Pacific/Fakaofo", Integer.valueOf(482));
    zoneid.put("Pacific/Fiji", Integer.valueOf(454));
    zoneid.put("Pacific/Funafuti", Integer.valueOf(484));
    zoneid.put("Pacific/Galapagos", Integer.valueOf(452));
    zoneid.put("Pacific/Gambier", Integer.valueOf(455));
    zoneid.put("Pacific/Guadalcanal", Integer.valueOf(481));
    zoneid.put("Pacific/Guam", Integer.valueOf(458));
    zoneid.put("Pacific/Honolulu", Integer.valueOf(450));
    zoneid.put("Pacific/Kiritimati", Integer.valueOf(461));
    zoneid.put("Pacific/Kosrae", Integer.valueOf(468));
    zoneid.put("Pacific/Majuro", Integer.valueOf(463));
    zoneid.put("Pacific/Marquesas", Integer.valueOf(456));
    zoneid.put("Pacific/Nauru", Integer.valueOf(469));
    zoneid.put("Pacific/Niue", Integer.valueOf(473));
    zoneid.put("Pacific/Norfolk", Integer.valueOf(474));
    zoneid.put("Pacific/Noumea", Integer.valueOf(470));
    zoneid.put("Pacific/Pago_Pago", Integer.valueOf(478));
    zoneid.put("Pacific/Palau", Integer.valueOf(475));
    zoneid.put("Pacific/Pitcairn", Integer.valueOf(477));
    zoneid.put("Pacific/Ponape", Integer.valueOf(467));
    zoneid.put("Pacific/Port_Moresby", Integer.valueOf(476));
    zoneid.put("Pacific/Rarotonga", Integer.valueOf(453));
    zoneid.put("Pacific/Saipan", Integer.valueOf(462));
    zoneid.put("Pacific/Tahiti", Integer.valueOf(457));
    zoneid.put("Pacific/Tarawa", Integer.valueOf(459));
    zoneid.put("Pacific/Tongatapu", Integer.valueOf(483));
    zoneid.put("Pacific/Truk", Integer.valueOf(466));
    zoneid.put("Pacific/Wake", Integer.valueOf(487));
    zoneid.put("Pacific/Wallis", Integer.valueOf(489));

    zoneid.put("Africa/Brazzaville", Integer.valueOf(41));
    zoneid.put("Egypt", Integer.valueOf(556));
    zoneid.put("Africa/Ceuta", Integer.valueOf(81));
    zoneid.put("Africa/El_Aaiun", Integer.valueOf(62));
    zoneid.put("Libya", Integer.valueOf(568));
    zoneid.put("America/Atka", Integer.valueOf(620));
    zoneid.put("US/Aleutian", Integer.valueOf(1132));
    zoneid.put("US/Alaska", Integer.valueOf(618));
    zoneid.put("America/Araguaina", Integer.valueOf(186));
    zoneid.put("America/Belem", Integer.valueOf(184));
    zoneid.put("America/Boa_Vista", Integer.valueOf(191));
    zoneid.put("America/Boise", Integer.valueOf(110));
    zoneid.put("America/Cambridge_Bay", Integer.valueOf(135));
    zoneid.put("America/Cancun", Integer.valueOf(140));
    zoneid.put("America/Catamarca", Integer.valueOf(179));
    zoneid.put("CST6CDT", Integer.valueOf(215));
    zoneid.put("US/Central", Integer.valueOf(613));
    zoneid.put("America/Chihuahua", Integer.valueOf(142));
    zoneid.put("America/Cordoba", Integer.valueOf(177));
    zoneid.put("America/Dawson", Integer.valueOf(139));
    zoneid.put("America/Shiprock", Integer.valueOf(1638));
    zoneid.put("MST7MDT", Integer.valueOf(216));
    zoneid.put("Navajo", Integer.valueOf(614));
    zoneid.put("US/Mountain", Integer.valueOf(1126));
    zoneid.put("America/Detroit", Integer.valueOf(116));
    zoneid.put("US/Michigan", Integer.valueOf(628));
    zoneid.put("Canada/Mountain", Integer.valueOf(641));
    zoneid.put("America/Glace_Bay", Integer.valueOf(121));
    zoneid.put("America/Goose_Bay", Integer.valueOf(119));
    zoneid.put("Canada/Atlantic", Integer.valueOf(632));
    zoneid.put("Cuba", Integer.valueOf(665));
    zoneid.put("America/Hermosillo", Integer.valueOf(143));
    zoneid.put("America/Indiana/Knox", Integer.valueOf(113));
    zoneid.put("America/Knox_IN", Integer.valueOf(625));
    zoneid.put("US/Indiana-Starke", Integer.valueOf(1137));
    zoneid.put("America/Indiana/Marengo", Integer.valueOf(112));
    zoneid.put("America/Indiana/Vevay", Integer.valueOf(114));
    zoneid.put("America/Fort_Wayne", Integer.valueOf(623));
    zoneid.put("America/Indiana/Indianapolis", Integer.valueOf(1647));
    zoneid.put("America/Indiana/Vincennes", Integer.valueOf(209));
    zoneid.put("America/Indiana/Petersburg", Integer.valueOf(210));

    zoneid.put("US/East-Indiana", Integer.valueOf(1135));
    zoneid.put("America/Inuvik", Integer.valueOf(137));
    zoneid.put("America/Iqaluit", Integer.valueOf(133));
    zoneid.put("Jamaica", Integer.valueOf(674));
    zoneid.put("America/Jujuy", Integer.valueOf(178));
    zoneid.put("America/Juneau", Integer.valueOf(104));
    zoneid.put("PST8PDT", Integer.valueOf(217));
    zoneid.put("US/Pacific", Integer.valueOf(615));
    zoneid.put("US/Pacific-New", Integer.valueOf(1639));
    zoneid.put("America/Louisville", Integer.valueOf(115));
    zoneid.put("America/Maceio", Integer.valueOf(187));
    zoneid.put("Brazil/West", Integer.valueOf(704));
    zoneid.put("Mexico/BajaSur", Integer.valueOf(656));
    zoneid.put("America/Mendoza", Integer.valueOf(180));
    zoneid.put("America/Menominee", Integer.valueOf(117));
    zoneid.put("Mexico/General", Integer.valueOf(653));
    zoneid.put("Canada/Eastern", Integer.valueOf(634));
    zoneid.put("EST5EDT", Integer.valueOf(214));
    zoneid.put("US/Eastern", Integer.valueOf(612));
    zoneid.put("America/Nipigon", Integer.valueOf(124));
    zoneid.put("America/Nome", Integer.valueOf(107));
    zoneid.put("Brazil/DeNoronha", Integer.valueOf(695));
    zoneid.put("America/Pangnirtung", Integer.valueOf(132));

    zoneid.put("US/Arizona", Integer.valueOf(621));
    zoneid.put("Brazil/Acre", Integer.valueOf(705));
    zoneid.put("America/Porto_Velho", Integer.valueOf(190));
    zoneid.put("America/Rainy_River", Integer.valueOf(125));
    zoneid.put("America/Rankin_Inlet", Integer.valueOf(134));
    zoneid.put("Canada/East-Saskatchewan", Integer.valueOf(639));
    zoneid.put("Canada/Saskatchewan", Integer.valueOf(1151));
    zoneid.put("America/Rosario", Integer.valueOf(176));
    zoneid.put("Chile/Continental", Integer.valueOf(706));
    zoneid.put("Brazil/East", Integer.valueOf(700));
    zoneid.put("Canada/Newfoundland", Integer.valueOf(630));
    zoneid.put("America/Virgin", Integer.valueOf(686));
    zoneid.put("America/Swift_Current", Integer.valueOf(128));
    zoneid.put("America/Thunder_Bay", Integer.valueOf(123));
    zoneid.put("America/Ensenada", Integer.valueOf(657));
    zoneid.put("Mexico/BajaNorte", Integer.valueOf(1169));
    zoneid.put("Canada/Pacific", Integer.valueOf(642));
    zoneid.put("America/Whitehorse", Integer.valueOf(138));
    zoneid.put("Canada/Yukon", Integer.valueOf(650));
    zoneid.put("Canada/Central", Integer.valueOf(638));
    zoneid.put("America/Yakutat", Integer.valueOf(105));
    zoneid.put("America/Yellowknife", Integer.valueOf(136));
    zoneid.put("Antarctica/Davis", Integer.valueOf(231));
    zoneid.put("Antarctica/South_Pole", Integer.valueOf(748));
    zoneid.put("Antarctica/Syowa", Integer.valueOf(234));
    zoneid.put("Asia/Almaty", Integer.valueOf(269));
    zoneid.put("Asia/Chungking", Integer.valueOf(251));
    zoneid.put("Asia/Dili", Integer.valueOf(259));
    zoneid.put("Asia/Gaza", Integer.valueOf(285));
    zoneid.put("Asia/Harbin", Integer.valueOf(249));
    zoneid.put("Hongkong", Integer.valueOf(766));
    zoneid.put("Asia/Hovd", Integer.valueOf(280));
    zoneid.put("Asia/Istanbul", Integer.valueOf(1431));
    zoneid.put("Asia/Tel_Aviv", Integer.valueOf(778));
    zoneid.put("Israel", Integer.valueOf(1290));
    zoneid.put("Asia/Kashgar", Integer.valueOf(253));
    zoneid.put("Asia/Kuching", Integer.valueOf(279));
    zoneid.put("Asia/Omsk", Integer.valueOf(304));
    zoneid.put("Asia/Riyadh87", Integer.valueOf(289));
    zoneid.put("Mideast/Riyadh87", Integer.valueOf(801));
    zoneid.put("Asia/Riyadh88", Integer.valueOf(290));
    zoneid.put("Mideast/Riyadh88", Integer.valueOf(802));
    zoneid.put("Asia/Riyadh89", Integer.valueOf(291));
    zoneid.put("Mideast/Riyadh89", Integer.valueOf(803));
    zoneid.put("Asia/Samarkand", Integer.valueOf(299));
    zoneid.put("ROK", Integer.valueOf(785));
    zoneid.put("PRC", Integer.valueOf(762));
    zoneid.put("Singapore", Integer.valueOf(804));
    zoneid.put("ROC", Integer.valueOf(767));
    zoneid.put("Iran", Integer.valueOf(776));
    zoneid.put("Japan", Integer.valueOf(779));
    zoneid.put("Asia/Ulaanbaatar", Integer.valueOf(281));
    zoneid.put("Asia/Urumqi", Integer.valueOf(252));
    zoneid.put("Atlantic/Madeira", Integer.valueOf(337));
    zoneid.put("Iceland", Integer.valueOf(846));
    zoneid.put("Australia/South", Integer.valueOf(861));
    zoneid.put("Australia/Queensland", Integer.valueOf(859));
    zoneid.put("Australia/Broken_Hill", Integer.valueOf(353));
    zoneid.put("Australia/Yancowinna", Integer.valueOf(865));
    zoneid.put("Australia/North", Integer.valueOf(857));
    zoneid.put("Australia/Hobart", Integer.valueOf(350));
    zoneid.put("Australia/Tasmania", Integer.valueOf(862));
    zoneid.put("Australia/Lindeman", Integer.valueOf(348));
    zoneid.put("Australia/Lord_Howe", Integer.valueOf(354));
    zoneid.put("Australia/LHI", Integer.valueOf(866));
    zoneid.put("Australia/Melbourne", Integer.valueOf(351));
    zoneid.put("Australia/Victoria", Integer.valueOf(863));
    zoneid.put("Australia/West", Integer.valueOf(858));
    zoneid.put("Australia/Canberra", Integer.valueOf(1376));
    zoneid.put("Australia/NSW", Integer.valueOf(1888));
    zoneid.put("CET", Integer.valueOf(366));
    zoneid.put("Etc/GMT", Integer.valueOf(1));
    zoneid.put("Etc/GMT+0", Integer.valueOf(1025));
    zoneid.put("Etc/GMT-0", Integer.valueOf(2049));
    zoneid.put("Etc/GMT0", Integer.valueOf(3073));
    zoneid.put("Etc/Greenwich", Integer.valueOf(4097));
    zoneid.put("GMT+0", Integer.valueOf(1537));
    zoneid.put("GMT-0", Integer.valueOf(2561));
    zoneid.put("GMT0", Integer.valueOf(3585));
    zoneid.put("Greenwich", Integer.valueOf(4609));
    zoneid.put("Etc/GMT+1", Integer.valueOf(16));
    zoneid.put("Etc/GMT+10", Integer.valueOf(25));
    zoneid.put("Etc/GMT+11", Integer.valueOf(26));
    zoneid.put("Etc/GMT+12", Integer.valueOf(27));
    zoneid.put("Etc/GMT+2", Integer.valueOf(17));
    zoneid.put("Etc/GMT+3", Integer.valueOf(18));
    zoneid.put("Etc/GMT+4", Integer.valueOf(19));
    zoneid.put("Etc/GMT+5", Integer.valueOf(20));
    zoneid.put("Etc/GMT+6", Integer.valueOf(21));
    zoneid.put("Etc/GMT+7", Integer.valueOf(22));
    zoneid.put("Etc/GMT+8", Integer.valueOf(23));
    zoneid.put("Etc/GMT+9", Integer.valueOf(24));
    zoneid.put("Etc/GMT-1", Integer.valueOf(15));
    zoneid.put("Etc/GMT-10", Integer.valueOf(6));
    zoneid.put("Etc/GMT-11", Integer.valueOf(5));
    zoneid.put("Etc/GMT-12", Integer.valueOf(4));
    zoneid.put("Etc/GMT-13", Integer.valueOf(3));
    zoneid.put("Etc/GMT-14", Integer.valueOf(2));
    zoneid.put("Etc/GMT-2", Integer.valueOf(14));
    zoneid.put("Etc/GMT-3", Integer.valueOf(13));
    zoneid.put("Etc/GMT-4", Integer.valueOf(12));
    zoneid.put("Etc/GMT-5", Integer.valueOf(11));
    zoneid.put("Etc/GMT-6", Integer.valueOf(10));
    zoneid.put("Etc/GMT-7", Integer.valueOf(9));
    zoneid.put("Etc/GMT-8", Integer.valueOf(8));
    zoneid.put("Etc/GMT-9", Integer.valueOf(7));
    zoneid.put("Europe/Belfast", Integer.valueOf(370));
    zoneid.put("Europe/Ljubljana", Integer.valueOf(924));
    zoneid.put("Europe/Sarajevo", Integer.valueOf(1436));
    zoneid.put("Europe/Skopje", Integer.valueOf(1948));
    zoneid.put("Europe/Zagreb", Integer.valueOf(2460));
    zoneid.put("Eire", Integer.valueOf(883));
    zoneid.put("Turkey", Integer.valueOf(919));
    zoneid.put("Portugal", Integer.valueOf(911));
    zoneid.put("GB", Integer.valueOf(881));
    zoneid.put("GB-Eire", Integer.valueOf(1393));
    zoneid.put("W-SU", Integer.valueOf(914));
    zoneid.put("Europe/Bratislava", Integer.valueOf(890));
    zoneid.put("Europe/San_Marino", Integer.valueOf(1411));
    zoneid.put("Europe/Vatican", Integer.valueOf(899));
    zoneid.put("Europe/Tiraspol", Integer.valueOf(394));
    zoneid.put("Europe/Uzhgorod", Integer.valueOf(409));
    zoneid.put("Poland", Integer.valueOf(910));
    zoneid.put("Europe/Zaporozhye", Integer.valueOf(410));
    zoneid.put("NZ", Integer.valueOf(983));
    zoneid.put("NZ-CHAT", Integer.valueOf(984));
    zoneid.put("Chile/EasterIsland", Integer.valueOf(963));
    zoneid.put("US/Hawaii", Integer.valueOf(962));
    zoneid.put("Pacific/Johnston", Integer.valueOf(485));
    zoneid.put("Pacific/Kwajalein", Integer.valueOf(464));
    zoneid.put("Kwajalein", Integer.valueOf(976));
    zoneid.put("Pacific/Midway", Integer.valueOf(486));
    zoneid.put("Pacific/Samoa", Integer.valueOf(1502));
    zoneid.put("US/Samoa", Integer.valueOf(990));
    zoneid.put("Pacific/Yap", Integer.valueOf(465));
    zoneid.put("WET", Integer.valueOf(365));

    zoneid.putOld("EST", new Integer(1636));
    zoneid.putOld("UTC", new Integer(540));
    zoneid.putOld("MST", new Integer(2662));
    zoneid.putOld("HST", new Integer(1474));
    zoneid.putOld("CST6CDT", new Integer(1125));
    zoneid.putOld("MST7MDT", new Integer(2150));
    zoneid.putOld("PST8PDT", new Integer(1127));
    zoneid.putOld("EST5EDT", new Integer(1124));
  }
}